
[spice]

# Base kernels
kernels = [
    "kernels/pck/pck00010.tpc",
    "kernels/fk/juno_v12.tf",
    "kernels/ik/juno_junocam_v03.ti",
    "kernels/lsk/naif0012.tls", 
    "kernels/sclk/jno_sclkscet_00074.tsc",
    "kernels/spk/juno_struct_v04.bsp"
]

# Spacecraft Pointing
ck_rec_pattern = "kernels/ck/juno_sc_rec_??????_??????_v??.bc"
ck_pre_pattern = "kernels/ck/juno_sc_raw_??????_??????.bc"
ck_nth_start_date = 3
ck_nth_end_date = 4

spk_rec_pattern = "kernels/spk/juno_rec_??????_??????_??????.bsp"
spk_pre_pattern = "kernels/spk/spk_pre_??????_??????_??????_?????_?.bsp"
spk_nth_start_date = 2
spk_nth_end_date = 3

[calibration]
dark_red = "junocam_dark_pj28_v1_red.tif"
dark_green = "junocam_dark_pj28_v1_green.tif"
dark_blue = "junocam_dark_pj28_v1_blue.tif"

inpaint_red = "junocam_inpaint_mask_pj32_v1_red.png"
inpaint_green = "junocam_inpaint_mask_pj32_v1_green.png"
inpaint_blue = "junocam_inpaint_mask_pj32_v1_blue.png"

flat_red = "junocam_rgb_flatfield_v3_2.png"
flat_green = "junocam_rgb_flatfield_v3_1.png"
flat_blue = "junocam_rgb_flatfield_v3_0.png"

[defaults]
red_weight = 0.902
green_weight = 1.0
blue_weight = 1.8879
camera_lens_projection = "fisheye"
fisheye_field_of_view = 180.0
interframe_delay_correction = 0.001
start_time_correction = 0.06188
apply_calibration = true
apply_infill_correction = true
apply_hot_pixel_correction = true
hpc_window_size = 5
hpc_threshold = 2.0
apply_weights = true
correlated_color_balancing = false