[package]
name = "junocam_processing"
version = "0.1.0"
authors = ["Kevin M. Gill <apoapsys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["opencv-4"]
clang-runtime = ["clang/runtime"]
opencv-32 = []
opencv-34 = []
opencv-4 = []
contrib = []
docs-only = []

[dependencies]
image = "0.23.14"
clap = "2.33.3"
spice = "0.1.0"
opencv = "0.49.1"
zip = "0.5.11"

[build-dependencies]
clang = { version = "1.0", features = ["clang_6_0"], optional = true }
